### PR TITLE
Add SSD1306 display to demo

### PR DESCRIPTION
**Pull request by lutzky**
The main reason I was looking for a way to simulate ESPhome is to simplify pixel-peeping of SSD1306 graphics. The initial config has a few pitfalls, so I thought it might be helpful to include it in the demo.

### CODE REVIEW

**Comment by the-mentor** [comment]
Hi @lutzky thank you very much for the PR.

Is pillow a requirement of esphome?
Without it the firmware wouldn't compile?

**Comment by lutzky** [comment]
Thank you for the project! It was honestly something I'd been trying to do without much success until I encountered your repo.

`pillow` is a requirement of esphome's `display` component. After adding a `display` to the esphome YAML config, the firmware won't compile without `pillow`.

**Comment by the-mentor** [comment]
@lutzky I'm happy to see my work helped someone the way it helped me.

after doing some testing looks like on windows you also need to install the `python-magic-bin` package for the code to compile otherwise you get a weird error about file not found.
so can you please add `python -m pip install python-magic-bin==0.4.14 ` and `python3 -m pip install python-magic-bin==0.4.14`  to the venv setup scripts and then i'll merge the code.

**Comment by lutzky** [comment]
This fails on Linux:

```
$ pip install python-magic-bin==0.4.14
ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from versions: none)
ERROR: No matching distribution found for python-magic-bin==0.4.14
```

Indeed, https://pypi.org/project/python-magic-bin/0.4.14/ only appears to have Windows files. However, the build (`esphome compile`) works fine on Linux without it. I'll update instructions accordingly.

**Pull request merged**
